[project]
name = "maple-font"
version = "7.8"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "foundrytools-cli==2.0.2",
    "glyphslib==6.12.0",
    "python-minifier==3.1.0",
    "setuptools==80.0.0"
]
