name: Sync Fork

on:
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_repository: subframe7536/maple-font
          target_repository: lecodeski/maple-font
          upstream_branch: variable
          target_branch: main
          tags: true